// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq196Qv4iA_vt2wJw6d7-EdKWb5coMAUs',
    appId: '1:174431143089:android:50cb20d610687a1b474e90',
    messagingSenderId: '174431143089',
    projectId: 'fooddelivery-b6b10',
    storageBucket: 'fooddelivery-b6b10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB38vJXJKJ7LKyBnb4Md1M57uVFHAWBOgY',
    appId: '1:174431143089:ios:90c053b816097690474e90',
    messagingSenderId: '174431143089',
    projectId: 'fooddelivery-b6b10',
    storageBucket: 'fooddelivery-b6b10.appspot.com',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYHq4Y6bLjV-0mZ0X42Wbjn58_HyGWTFQ',
    appId: '1:174431143089:web:0c4f3d6daa2d1946474e90',
    messagingSenderId: '174431143089',
    projectId: 'fooddelivery-b6b10',
    authDomain: 'fooddelivery-b6b10.firebaseapp.com',
    storageBucket: 'fooddelivery-b6b10.appspot.com',
    measurementId: 'G-KYF87Y0TE6',
  );

}